#Resource definition of the lambda function itself
resource "aws_lambda_function" "lambda_function" {
  function_name = var.function_name
  filename     =  var.filename
  role         =  aws_iam_role.lambda_execution.arn
  handler      =  var.handler
  runtime      =  var.language
}

#IAM roles to execute Lambda
resource "aws_iam_role" "lambda_execution" {
  name = "lambda_lusk_execution"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "lambda_execution_policy_attachment" {
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  role       = aws_iam_role.lambda_execution.name
}

#Permission to allow API Gateway execute Lambda fucntion
resource "aws_lambda_permission" "api_gateway" {
  statement_id  = "AllowExecutionFromAPIGateway"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.lambda_function.function_name
  principal     = "apigateway.amazonaws.com"
}

#Defining API Gateway rest api as a resource
resource "aws_api_gateway_rest_api" "lusk_api" {
  name        = var.function_name
  description = "API auto-generated by Lusk automation for respective Lambda Function"
}

#Defining API Gateway as a resource
resource "aws_api_gateway_resource" "lusk_api_resource" {
  rest_api_id = aws_api_gateway_rest_api.lusk_api.id
  parent_id   = aws_api_gateway_rest_api.lusk_api.root_resource_id
  path_part   = "execution"
}

#Defining the http methpod that will interact with the API
resource "aws_api_gateway_method" "post_method" {
  rest_api_id   = aws_api_gateway_rest_api.lusk_api.id
  resource_id   = aws_api_gateway_resource.lusk_api_resource.id
  http_method   = "POST"
  authorization = "NONE"

  request_parameters = {
    "method.request.header.Authorization" = true
  }
}

#Defining API Gateway integration with Lambda function
resource "aws_api_gateway_integration" "lambda_integration" {
  depends_on = [aws_lambda_function.lambda_function]
  rest_api_id = aws_api_gateway_rest_api.lusk_api.id
  resource_id = aws_api_gateway_resource.lusk_api_resource.id
  http_method = aws_api_gateway_method.post_method.http_method

  integration_http_method = "POST"
  type                    = "AWS_PROXY"
  uri                     = aws_lambda_function.lambda_function.invoke_arn
}

#Defining API Gateway deployment
resource "aws_api_gateway_deployment" "api_deployment" {
  depends_on = [
    aws_api_gateway_integration.lambda_integration
  ]
  rest_api_id = aws_api_gateway_rest_api.lusk_api.id
  stage_name  = "prod"
}

module "cors" {
  source = "squidfunk/api-gateway-enable-cors/aws"
  version = "0.3.3"

  api_id          = aws_api_gateway_rest_api.lusk_api.id
  api_resource_id = aws_api_gateway_resource.lusk_api_resource.id
}

#Defining API Gateway URL as output to consume afterwards the creation
output "api_endpoint" {
  value = aws_api_gateway_deployment.api_deployment.invoke_url
}